"""Build a portable Windows release with notes and SHA-256 checksums."""
from __future__ import annotations

import hashlib
from pathlib import Path
import platform
import shutil
import subprocess
import sys
from zipfile import ZIP_DEFLATED, ZipFile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from wardogs_mortar import __version__


def main():
    if sys.platform != "win32" or sys.maxsize <= 2**32 or platform.machine().lower() not in ("amd64", "x86_64"):
        raise SystemExit("Build this Windows x64 release on Windows x64.")
    subprocess.run([sys.executable, "tools/prepare_distribution.py"], cwd=ROOT, check=True)
    subprocess.run([sys.executable, "-m", "PyInstaller", "WardogsMortar.spec", "--noconfirm", "--log-level", "WARN"], cwd=ROOT, check=True)
    dist = ROOT / "dist"
    application = dist / "WardogsMortar"
    for name in ("README.md", "CHANGELOG.md", "LICENSE"):
        if (ROOT / name).is_file():
            shutil.copy2(ROOT / name, application / name)
    archive = dist / f"WardogsMortar-v{__version__}-Windows-x64.zip"
    with ZipFile(archive, "w", ZIP_DEFLATED, compresslevel=6) as output:
        for path in sorted(application.rglob("*")):
            if path.is_file():
                output.write(path, path.relative_to(dist))
    with archive.open("rb") as stream:
        digest = hashlib.file_digest(stream, "sha256").hexdigest()
    (dist / "SHA256SUMS.txt").write_text(f"{digest}  {archive.name}\n", encoding="utf-8")
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    changes = changelog.split(f"## {__version__}\n", 1)[1].split("\n## ", 1)[0].strip()
    notes = f"""# WARDOGS Mortar Calculator v{__version__}

{changes}

## 下载与运行 / Download and run

下载 `{archive.name}`，完整解压后运行 `WardogsMortar/WardogsMortar.exe`。需要 Windows 10/11 x64，无需安装 Python。请保留 `_internal` 文件夹。可使用 `SHA256SUMS.txt` 核对下载文件。

Download `{archive.name}`, extract it completely, and run `WardogsMortar/WardogsMortar.exe`. Requires Windows 10/11 x64; Python is not required. Keep the `_internal` folder. Verify the download using `SHA256SUMS.txt`.

F1 记录炮位，F2 记录目标，F3 切换悬浮窗；快捷键可在设置中修改。设置旁的地球图标切换中英文。

F1 captures the gun, F2 captures the target, and F3 toggles the overlay. Hotkeys are configurable in Settings. The globe icon beside Settings switches between Chinese and English.

MIL 使用 132–684 米的社区平地射表，不含高差修正。本项目由 GPT-6 Astra 生成，是非官方社区工具。

MIL uses a community flat-ground firing table for 132–684 meters, without elevation-difference correction. Generated by GPT-6 Astra; an unofficial community tool.
"""
    (dist / "RELEASE_NOTES.md").write_text(notes, encoding="utf-8")
    print(f"Release: {archive}\nSize: {archive.stat().st_size / 1024**2:.1f} MiB\nSHA-256: {digest}")


if __name__ == "__main__":
    main()
